version: '3'
services:
  mongo:
    image: "mongo"
    container_name: "mongo"
    env_file:
      - env4dc.env
    ports:
     - "27017:27017"

  subscriber:
    image: "subscriber_r2"
    container_name: "subscriber"
    environment:
      - mqServer=redis
      - drUrl=mongodb://mongo:27017/vsr
    env_file:
      - env4dc.env
    depends_on:
      - "mongo"

  metadata:
    image: "metadata_r2"
    container_name: "metadata"
    environment:
      - drUrl=mongodb://mongo:27017/vsr
    env_file:
      - env4dc.env
    depends_on:
      - "mongo"


  utils:
    image: "utils"
    container_name: "utils"
    environment:
      - drUrl=mongodb://mongo:27017/vsr
    env_file:
      - env4dc.env
    depends_on:
      - "subscriber"
      - "mongo"
