FROM alpine
RUN apk add --update nodejs
RUN apk add --update npm
RUN apk add --update bash

WORKDIR /usr

COPY package*.json ./

COPY packages/AWS/* ./AWS/
COPY packages/metadata/*.js ./metadata/

RUN npm ci --only=production
EXPOSE 8081
CMD [ "node", "metadata/" ]